### ISSUE TITLE
Garage Door Opener Integrated light

### ISSUE THREAD

**Issue by copart** [arraylabs/pymyq#133]
Hi,

Is there any way to remotely control the integrated LED on my Liftmaster WLED garage door opener? Control would be awesome, remote status would be better than nothing.

I see that pymyq supports the "light" accessories that are available, but does Liftmaster/Chamberlain really not expose this via API? This is crazy.

I would even love to have notify of "sense" when you walks in front of the buttons motion sensor and/or trip the photo eye/safety sensor.

**Comment by mbbush** [comment]
> I see that pymyq supports the "light" accessories that are available, but does Liftmaster/Chamberlain really not expose this via API? This is crazy.

Yes to both counts. I had a similar desire, as the garage door opener includes a light and a motion sensor I'd like to be able to use like the other lights and motion sensors in my smart home. But there's no api support at all, for either control or status. 

I'm extrapolating a little, but I imagine their reasoning is that since they couldn't think of anything to do with the light in their own app, they didn't include it in the api. Why they'd build a device category for "light" but then not include the light built into the garage door opener is beyond me, though. The api is definitely a funky one, and my understanding is that Chamberlain has expressed outright hostility to an official integration. The cynic in me assumes that's because they don't see how it would make them more money.

The only way I can think of to make this work would be opening up the unit and looking for physical headers or solder points which you could connect something to. This is almost certainly not worth the effort for the marginal gain, but if you ever explore it, please let me know.

**Comment by ehendrix23** [comment]
Unless we know the API call, if any, there is nothing we can do here. They do not publish the API and as mentioned even from their app the light is not supported.
